### ISSUE TITLE
Big Text Style/ Summary text

### ISSUE THREAD

**Issue by Arjunender** [andrehtissot/cordova-plugin-firebase-extended-notification#12]
1. How to set big text style 
2. Summary text is not displayed 

thanks

**Comment by andrehtissot** [comment]
Hi Arjunender,

Now it's supported with the new `bigText` option.

For details look here: [https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification/wiki/Big-Text-Option](https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification/wiki/Big-Text-Option)
