### ISSUE TITLE
Heads-up notification

### ISSUE THREAD

**Issue by ghost** [andrehtissot/cordova-plugin-firebase-extended-notification#14]
@andrehtissot, how to add Heads-up (peeking) notifications for Android?

**Comment by andrehtissot** [comment]
I'll check on that. New features are coming!

**Comment by ghost** [comment]
Nice work @andrehtissot! Do have an idea of the timeframe for implementing this feature?

**Comment by robertojf2012** [comment]
How can I install this plugin in ionic Cordova?

**Comment by andrehtissot** [comment]
the same way you install any cordova plugin, since ionic is based on cordova:
`cordova plugin add cordova-plugin-firebase-extended-notification`

**Comment by robertojf2012** [comment]
Im getting an error, (exit code 1)  failed to fetch the plugin

**Comment by andrehtissot** [comment]
robertojf2012, please don't use other issues' threads talk about a different issue, it's not nice to those that want to know about this thread's issue "Heads-up notification".

And the failed to fetch the plugin error is that you weren't able to download it.
Which version are you using right now?

**Comment by robertojf2012** [comment]
sorry about that, im using ionic CLI 3.6.0.
or what do you mean by version? thank you

**Comment by andrehtissot** [comment]
Can you paste here the lines from executing the command: `cordova plugin add cordova-plugin-firebase-extended-notification`?

**Comment by robertojf2012** [comment]
ionic cordova plugin add cordova-plugin-firebase-extended-notification
> cordova plugin add cordova-plugin-firebase-extended-notification --save
× Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add cordova-plugin-firebase-extended-notification --save (exit
        code 1):

        Error: Failed to fetch plugin cordova-plugin-firebase-extended-notification via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm WARN addRemoteGit Error: not found: git
        npm WARN addRemoteGit     at getNotFoundError (C:\Program
        Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
        npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
        npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
        npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
        npm WARN addRemoteGit     at C:\Program
        Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
        npm WARN addRemoteGit     at C:\Program
        Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
        npm WARN addRemoteGit     at C:\Program
        Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
        npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
        npm WARN addRemoteGit  git+https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated.git
        resetting remote
        C:\Users\Robert\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-andrehtissot-cordova-plugin-fcm-with-dependecy-updated-git-c5f3e3aa
        because of error: { Error: not found: git
        npm WARN addRemoteGit     at getNotFoundError (C:\Program
        Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
        npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
        npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
        npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
        npm WARN addRemoteGit     at C:\Program
        Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
        npm WARN addRemoteGit     at C:\Program
        Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
        npm WARN addRemoteGit     at C:\Program
        Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
        npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
        npm ERR! git clone --template=C:\Users\Robert\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated.git
        C:\Users\Robert\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-andrehtissot-cordova-plugin-fcm-with-dependecy-updated-git-c5f3e3aa:
        undefined
        npm ERR! git clone --template=C:\Users\Robert\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated.git
        C:\Users\Robert\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-andrehtissot-cordova-plugin-fcm-with-dependecy-updated-git-c5f3e3aa:
        undefined
        npm ERR! Windows_NT 10.0.15063
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
        Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cordova-plugin-firebase-extended-notification"
        "--save"
        npm ERR! node v6.10.3
        npm ERR! npm  v3.10.10
        npm ERR! code ENOGIT

        npm ERR! not found: git
        npm ERR!
        npm ERR! Failed using git.
        npm ERR! This is most likely not a problem with npm itself.
        npm ERR! Please check if you have git installed and in your PATH.

        npm ERR! Please include the following file with any support request:
        npm ERR!     F:\AutoAlerts\AutoAlerts_App\AutoAlerts\node_modules\npm-debug.log

**Comment by andrehtissot** [comment]
You weren't able to download the dependency.
Try installing the plugin `cordova-plugin-fcm-with-dependecy-updated` before the `cordova plugin add cordova-plugin-firebase-extended-notification`.

**Comment by robertojf2012** [comment]
I have just done that, and it is not working either.. do I need to have installed the 'cordova-plugin-fcm'??
this what I did.
I removed the android platform
I unistalled cordova-plugin-fcm
I installed cordova-plugin-fcm-with-dependecy-updated
and then I tried to install cordova-plugin-firebase-extended-notification

but it fails with the same code..

**Comment by andrehtissot** [comment]
Hi @juniorlinn,

The option "headsUp" is now available, and can be easily tested on the [example app](https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification-app-example).

**Comment by ghost** [comment]
Thanks @andrehtissot, Can we define the duration of the heads-up notification as well? 
I.e.: The notification will stay on for 15 seconds if the user doesn't interact with the buttons?

**Comment by andrehtissot** [comment]
@juniorlinn I'm looking into it, and made a lot a tests. I has to be possible, since call notifications works for more than 6 or 7 seconds. But I'm having difficulties getting a consistent behavior.

**Comment by ghost** [comment]
@andrehtissot, thanks for looking into this! 
On another note ... This plugin's just an extension of the original one; I can use it normally as I would use the original Katzer plugin, right?

**Comment by andrehtissot** [comment]
It's actually a "extension" of a [fork](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated), with dependency definition and other small fixes, of [cordova-plugin-fcm from fechanique](https://github.com/fechanique/cordova-plugin-fcm), which, at that time, appeared to be the best version available.

And yeah, @juniorlinn, you still get the methods described [here](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated).

**Comment by ghost** [comment]
@andrehtissot, right! I mixed up the names ... :-)
