### ISSUE TITLE
register the app to a topic?

### ISSUE THREAD

**Issue by maxlinux2000** [andrehtissot/cordova-plugin-firebase-extended-notification#15]
Hello I have a problem with sending the push to all my apps.

So far, my apps send to my server the token and the id of the app.
Everything is saved in a database, so if I want to send a notification to an app (for example: com.example.app1), the database pulls me the entire token list from the com.example.myapp1 or com.example.myapp2.
Using a "for loop" I send the message to each of the token, using curl.

But this system takes quite a while and sometimes crashes with a 500 error.

So I thought of assigning each of my app a different topic, so that I could put in the "to:" field something like / topic / myapp1

But how do you do this in javascript?
How do I register the app to for example the topic: cantandocondios?

**Comment by maxlinux2000** [comment]
the problem was generated because all apps are sharing the same "Server key" because the server key is linked the the proj, and not to the single app.
In order to have differet Server key I need to ask (and pay) for many projects space... but I can't pay for that.... consider thatI have at the moment 16 apps published, 4 are buildings, and 3 in nursery :)

**Comment by andrehtissot** [comment]
I don't know if I understood the problem.
But take a look at this wiki page: [How To Send A Notification To All Users (Topics)](https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification/wiki/How-To-Send-A-Notification-To-All-Users-(Topics))

If it doesn't help you, send me another message.

**Comment by maxlinux2000** [comment]
I explain the problem with an example:

I have 2 app (app1 and app2), both are registered in the firebase console under the same project. So the server key is the same for both.

If I send a push message to "to: topics / all" which of the two apps will receive it?
I imagine that the two will receive the message, because in the message there is no way to tell which app to send it.

... or I do not know how to differentiate it.

What I have invented is another system, but it is a bit laborious. I practically incase the message written in a coded url where I indicate to which app to send the message (app1 for example).
The program receives the encoded url, searches the database for all the token of the users of the app1, and then sends each of it the message.
I'm practically recreating what Google already does on its servers, but I'd like to avoid it, because it's heavy on the VPS.

That's why I'm looking for a system to apply what you tell me about "to: topics / all" but from convertables to "to: topics / app1" or "to: topics / app2" ... and so on

**Comment by andrehtissot** [comment]
I haven't tested it, but both apps should receive the notification, since the both apps belongs the the same firebase project, and in that project there is only one server key.

For your case, I recommend to execute in JS `FCMPlugin.subscribeToTopic('appName');`, when the app starts.

Then when you need to send for all users of the app1, you just set the "to" parameter to "/topics/appName". This way you just use a nickname for each app.

&nbsp;

Example:
For app1, in the app:
```Javascript
document.addEventListener('deviceready', function(){
  FCMPlugin.subscribeToTopic('app1');
});
```
For app1, in the server, the `"to"` = `"/topics/app1"`


For app2, in the app:
```Javascript
document.addEventListener('deviceready', function(){
  FCMPlugin.subscribeToTopic('app2');
});
```
For app2, in the server, the `"to"` = `"/topics/app2"`


If it doesn't work, let me know.
