### ISSUE TITLE
Working with Firebase admin ?

### ISSUE THREAD

**Issue by mparpaillon** [andrehtissot/cordova-plugin-firebase-extended-notification#16]
Hi,

Thanks for the plugin.

I think I'm missing something. Is it supposed to work with firebase-admin or only via curl ?
I'm trying to call `admin.messaging().sendToTopic('myTopic', payload)` with this payload but I get an error
```
var payload = {
  data: {
    dataValuesToGetWhenClickedOn: '111',
    notificationOptions: {
      id: '4',
      title: 'Title test',
      text: 'Test message',
      smallIcon: 'drawable/icon',
      largeIcon: 'https://avatars2.githubusercontent.com/u/1174345?v=3&s=96',
      autoCancel: true,
      vibrate: [200,300,200,300],
      color: '0000ff',
      headsUp: true,
      sound: true
    }
  }
};
```

=> 'Messaging payload contains an invalid value for the "data.notificationOptions" property. Values must be strings.'

From the Firebase doc:

> Data message payloads are composed of custom key-value pairs with a few restrictions, including the fact that all values must be strings

https://firebase.google.com/docs/cloud-messaging/admin/send-messages#defining_the_message_payload

I'm probably missing something obvious...
Thanks again

**Comment by andrehtissot** [comment]
The `data` Firebase params, as you error message sugests, cannot include objects.
When the JSON above is sent via curl, it's received as a String and parsed to an JSONObject.

I've never personally used the Firebase Admin SDK, but it seems that you can send an stringified version of this. Something like:
```Node.js
var payload = {
  data: {
    dataValuesToGetWhenClickedOn: '111',
    notificationOptions: JSON.stringify({
      id: '4',
      title: 'Title test',
      text: 'Test message',
      smallIcon: 'drawable/icon',
      largeIcon: 'https://avatars2.githubusercontent.com/u/1174345?v=3&s=96',
      autoCancel: true,
      vibrate: [200,300,200,300],
      color: '0000ff',
      headsUp: true,
      sound: true
    })
  }
};
```

I know it's not as nice looking, but flatten it up to work within the limitations of the SDK seems not worth it, mixing notification plugin options and app-related data, and limits the configurations patterns we may have in the future.

What do you think? And most important, this change works in your case?

**Comment by mparpaillon** [comment]
Works great :) Thanks a lot
