### ISSUE TITLE
How to manually ask for permission on iOS

### ISSUE THREAD

**Issue by mparpaillon** [andrehtissot/cordova-plugin-firebase-extended-notification#18]
Hi,

I'd like to choose when to display the dialog asking the user for permission to send push notifications. Even when I remove onNotification, getToken or onTokenRefresh calls it keeps on asking for permission on first launch.

Thanks

**Comment by andrehtissot** [comment]
I'm sorry, I currently have no device to test it on.

I updated the dependencies to use the newest code, so it may do what you need. But I can't be sure.

**Comment by mparpaillon** [comment]
I'll check this more tomorrow but it seems to ask for permission without any call.
That's too bad since users won't accept that without knowing what they're subscribing to. Also it's really hard for them to reactivate this after refusing it :s

**Comment by mparpaillon** [comment]
In the plugin I used before this one there was this function `grantPermission`: https://github.com/arnesson/cordova-plugin-firebase#grantpermission-ios-only

Maybe by looking at the implementation on this plugin you could add something similar to your plugin ? I would do it honestly but I'm not a Android or iOS developer so I would have to learn those languages before...

**Comment by andrehtissot** [comment]
I currently have no Mac & iPhone to test. Maybe I'll be able in the near future.

But I'll leave this issue open. So someone may find this and fix it, or help me with it.

**Comment by andrehtissot** [comment]
The new version 2.2.0 has the current cordova-plugin-fcm-with-dependecy-updated, which has `FCMPlugin.requestPushPermissionIOS();`
