### ISSUE TITLE
How to use this plugin in my IONIC app

### ISSUE THREAD

**Issue by Neotrixsx** [andrehtissot/cordova-plugin-firebase-extended-notification#2]
Hi André Tissot,
I successfully implement [cordova-plugin-fcm](https://www.npmjs.com/package/cordova-plugin-fcm) in my IONIC application and its work perfectly in my devices, But I need to send large Icon  and a small icon  in the notification. I don't have much PHP knowledge. Please help me how to implement your plugin in my app. If you have any PHP file by which I send large icon and small icon in the notification. Please help me.

**Comment by andrehtissot** [comment]
Yes, why not?
Can you tell me how is your server sending push requests?

**Comment by Neotrixsx** [comment]
I try to send Notification to my app by using below code.
 --API access key from Google API's Console
 http://test.com/fcm.php?body=hekkl&title=hiiiiiiiii&id=fUCA2WWjc00:APA91bEGxKf2ivxp7Ys2ceO7V54YOxY2B2gLeWaEtDER4A5VSNpqunn48ScAYhwuSm7u_hiT3OcaWvLbobjYzXxOCVkAQUH-0FSjPr6tBZltCqyDfV54YOxY2B2gLeWaEt

     `<?php  define( 'API_ACCESS_KEY', 'api-key' );
            $registrationIds = array( $_GET['id'] );
            $style = "inbox"; //picture/inbox
            $summeryText = "Venha provar os nossos Gins";
            $icon = "http://gintonico.com/content/uploads/2015/03/fontenova.jpg";
            $picture = "http://media5.letsbonus.com/products/285000/285006/14014409744462-0-1700x690.jpg";

            //print_r($registrationIds); // exit();
            //prep the bundle
            $msg = array
            (
                'body' 	=> $_GET['body'],
                'title'		=> $_GET['title'],
                'style' => $style,
                'summaryText' => $summeryText,
                'icon' => $icon,
                'picture' => $picture,

                'vibrate'	=> 1,
                'sound'		=> 1,
            );

            print_r($msg); // exit();

            $fields = array
            (
                'registration_ids' 	=> $registrationIds,
                'notification'			=> $msg
            );

            $headers = array
            (
                'Authorization: key=' . API_ACCESS_KEY,
                'Content-Type: application/json'
            );

            $ch = curl_init();
            curl_setopt( $ch,CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send' );
            curl_setopt( $ch,CURLOPT_POST, true );
            curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
            curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
            curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
            curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
            $result = curl_exec($ch );
            curl_close( $ch );
            echo $result;
            ?>`

**Comment by andrehtissot** [comment]
Got it.

You should change these lines:
```
$msg = array
(
    'body'  => $_GET['body'],
    'title'     => $_GET['title'],
    'style' => $style,
    'summaryText' => $summeryText,
    'icon' => $icon,
    'picture' => $picture,

    'vibrate'   => 1,
    'sound'     => 1,
);

print_r($msg); // exit();

$fields = array
(
    'registration_ids'  => $registrationIds,
    'notification'          => $msg
);
```

To something like these:
```
$msg = array
(
    'notificationOptions' => array(
        'text'  => $_GET['body'],
        'title'     => $_GET['title'],
        'summary' => $summeryText,
        'smallIcon' => $icon,
        'largeIcon' => $picture,
        'vibrate'   => 1,
        'sound'     => 1
    )
);

print_r($msg); // exit();

$fields = array
(
    'to'  => $registrationIds,
    'data'          => $msg
);
```

Try it out.

**Comment by Neotrixsx** [comment]
I need to add anything in my application side??

**Comment by andrehtissot** [comment]
Besides this plugin, no.

You can look at the "adb logcat" to see if there is any problem, like not receiving the push notification.

**Comment by Neotrixsx** [comment]
I add  cordova-plugin-fcm  plugin only rather than I need to add anything in my application?
Till now I did not and any code of your plugin(cordova-plugin-firebase-extended-notification) in  my app.  I need to know that how to add in my application.

And after adding  your given code in my PHP it shows some error.

**Array ( [notificationOptions] => Array ( [text] => hekkl [title] => hiiiiiiiii [summary] => Venha provar os nossos Gins [smallIcon] => http://gintonico.com/content/uploads/2015/03/fontenova.jpg [largeIcon] => http://media5.letsbonus.com/products/285000/285006/14014409744462-0-1700x690.jpg [vibrate] => 1 [sound] => 1 ) ) Field "to" must be a JSON string: ["cqANV_b9dXw:APA91bEmmagw2GWCNxAeegqR0CfpKsjpyYYANcUSUx0dXH2vAhVxEH5uD4VVmZpPnvo4MLa9N3eHb3pRO8RmCQJ3cPiYBeLGHPVeYPU_dA14-a_i9rPqcuRc"]**

**Comment by andrehtissot** [comment]
Yeah, my bad, I forgot to tell to change line `$registrationIds = array( $_GET['id'] );` to `$registrationIds = $_GET['id'];`.

Besides, the cordova-plugin-fcm plugin requires that you your firebase-generated google-services.json in the "platforms/android/" directory, have you done that?

**Comment by Neotrixsx** [comment]
Yes, I have done that.

**Comment by andrehtissot** [comment]
Changing those lines should be enough to fix the given error.

**Comment by Neotrixsx** [comment]
Now notification sends successfully from my server, but it hasn't landed in my app. The Log shows like that:

![screenshot_2](https://cloud.githubusercontent.com/assets/7522102/21593904/61abbfbe-d142-11e6-93a7-050af57defea.png)

**Comment by andrehtissot** [comment]
I tested using the code bellow (with the info you gave):
```php
$fields = array(
  'to' => '_____ANDROID_REGISTRATION_CODE_____',
  'data' => array(
    'notificationOptions' => array(
      'text' => 'hekkl',
      'title' => 'hiiiiiiiii',
      'summary' => 'Venha provar os nossos Gins',
      'smallIcon' => 'http://gintonico.com/content/uploads/2015/03/fontenova.jpg', //currently only resource works, like "drawable/icon"
      'largeIcon' => 'http://media5.letsbonus.com/products/285000/285006/14014409744462-0-1700x690.jpg',
      'vibrate' => 1,
      'sound' => 1
  )
));
$headers = array(
  'Authorization:key=_____FIREBASE_AUTHORIZATION_KEY_____',
  'Content-Type:application/json'
);
$ch = curl_init();
curl_setopt($ch,CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
curl_setopt($ch,CURLOPT_POST, true);
curl_setopt($ch,CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch,CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch,CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch,CURLOPT_POSTFIELDS, json_encode($fields));
$result = curl_exec($ch);
curl_close($ch);
$result = json_decode($result, true);
if($result['failure']!=0)
  logError(json_encode(print_r($result, true)));
```
And I got the expected result:
![notification_example](https://cloud.githubusercontent.com/assets/1174345/21594439/d10f684e-d109-11e6-9718-a782de31b7af.png)

And the log:
```log
01-02 16:38:31.533  9586  9586 I FirebaseInitProvider: FirebaseApp initialization successful
01-02 16:38:31.545   791  1279 I ActivityManager: Process com.android.documentsui (pid 7975) has died
01-02 16:38:31.545   791  1279 D ActivityManager: cleanUpApplicationRecord -- 7975
01-02 16:38:31.574  9586  9611 D FCMPlugin: ==> MyFirebaseMessagingService onMessageReceived
01-02 16:38:31.575  9586  9611 D FCMPlugin: 	Key: notificationOptions Value: {"summary":"Venha provar os nossos Gins","sound":1,"largeIcon":"http:\/\/media5.letsbonus.com\/products\/285000\/285006\/14014409744462-0-1700x690.jpg","vibrate":1,"smallIcon":"http:\/\/gintonico.com\/content\/uploads\/2015\/03\/fontenova.jpg","text":"hekkl","title":"hiiiiiiiii"}
01-02 16:38:31.575  9586  9611 D FCMPlugin: 	Notification Data: {notificationOptions={"summary":"Venha provar os nossos Gins","sound":1,"largeIcon":"http:\/\/media5.letsbonus.com\/products\/285000\/285006\/14014409744462-0-1700x690.jpg","vibrate":1,"smallIcon":"http:\/\/gintonico.com\/content\/uploads\/2015\/03\/fontenova.jpg","text":"hekkl","title":"hiiiiiiiii"}, wasTapped=false}
01-02 16:38:31.575  9586  9611 D FCMPlugin: ==> FCMPlugin sendPushPayload
01-02 16:38:31.576  9586  9611 D FCMPlugin: 	notificationCallBackReady: false
01-02 16:38:31.576  9586  9611 D FCMPlugin: 	gWebView: null
01-02 16:38:31.577  9586  9611 D FCMPlugin: 	payload: notificationOptions => {"summary":"Venha provar os nossos Gins","sound":1,"largeIcon":"http:\/\/media5.letsbonus.com\/products\/285000\/285006\/14014409744462-0-1700x690.jpg","vibrate":1,"smallIcon":"http:\/\/gintonico.com\/content\/uploads\/2015\/03\/fontenova.jpg","text":"hekkl","title":"hiiiiiiiii"}
01-02 16:38:31.577  9586  9611 D FCMPlugin: 	payload: wasTapped => false
01-02 16:38:31.577  9586  9611 D FCMPlugin: 	View not ready. SAVED NOTIFICATION: javascript:FCMPlugin.onNotificationReceived({"notificationOptions":"{\"summary\":\"Venha provar os nossos Gins\",\"sound\":1,\"largeIcon\":\"http:\\\/\\\/media5.letsbonus.com\\\/products\\\/285000\\\/285006\\\/14014409744462-0-1700x690.jpg\",\"vibrate\":1,\"smallIcon\":\"http:\\\/\\\/gintonico.com\\\/content\\\/uploads\\\/2015\\\/03\\\/fontenova.jpg\",\"text\":\"hekkl\",\"title\":\"hiiiiiiiii\"}","wasTapped":false})
```

Can yout try using my code and changing only those two keys to test it?

**Comment by Neotrixsx** [comment]
When my application is on background or close notification not shown on device tray, and when I remove
**'notificationOptions'**  and use my old PHP code, then notification show on device tray.

Old PHP code:
`    $msg = array
    (
        'body'  => $_GET['body'],
        'title'     => $_GET['title'],
        'style' => $style,
        'summaryText' => $summeryText,
        'icon' => $icon,
        'picture' => $picture,
        'vibrate'   => 1,
        'sound'     => 1,
    );

    print_r($msg); // exit();

    $fields = array
    (
    'registration_ids'  => $registrationIds,
    'notification'          => $msg
    );`


![screenshot_1](https://cloud.githubusercontent.com/assets/7522102/21599335/09d871ca-d191-11e6-9708-d085c0d42fd1.png)


Please share your Sample Application Code and PHP code with me, So I check what I am doing wrong with my app.

**Comment by Neotrixsx** [comment]
Hi André Tissot,
I am waiting for you help. Please share(via google drive) your Sample Application Code and PHP code with me, So I check what I am doing wrong with my app.

**Comment by andrehtissot** [comment]
Hi Neotrixsx.

I'm preparing an example app to publish here.

**Comment by Neotrixsx** [comment]
ok

**Comment by andrehtissot** [comment]
Hi Neotrixsx,

Look here: [https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification-app-example](https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification-app-example).

It's not Ionic, but I try to make it is as simple as I could, and worked on all my android devices.

**Comment by Neotrixsx** [comment]
Thanks, For example Now my app gets an image in notifications. You created a great plugin. Awesome!!!

**Comment by Neotrixsx** [comment]
I face a strange problem that now vibrate and sound not working when notification landed on the device.

**Comment by andrehtissot** [comment]
Let me look at it.

**Comment by andrehtissot** [comment]
It didn't supported sound and vibration, now it does.
