### ISSUE TITLE
Error duplicate 

### ISSUE THREAD

**Issue by jonataslaw** [andrehtissot/cordova-plugin-firebase-extended-notification#20]
I try to use this plugin many times, but this error always happens

Element provider#android.support.v4.content.FileProvider at AndroidManifest.xml:41:9-43:20 duplicated with element declared at AndroidManifest.xml:12:9-14:20

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:processArmv7DebugManifest FAILED

C:\Users\Jonatas Borges\Desktop\sandbox\platforms\android\AndroidManifest.xml Error:
        Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by andrehtissot** [comment]
Hi @jonataslaw,

#### Error
From the error message, seems that there is more than one FileProvider declared in your AndroidManifest.xml.

#### Plugin
The cordova-plugin-firebase-extended-notification plugin adds this provider below:
```XML
<provider android:name="android.support.v4.content.FileProvider"
    android:authorities="$PACKAGE_NAME.fbenfileprovider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/firebaseextendednotification_provider_paths"/>
</provider>
```
Obs.: `$PACKAGE_NAME` is replaced for the apps package name, allowing this plugin to be used in more than one installed app.

#### Analisis
From what I've read it should be fine having more than one provider, even the same kind. The only required param to be unique is `android:authorities`. Which the sufix `.fbenfileprovider` should take care of.

#### Conclusion
To help you, I'd need to take a look into your AndroidManifest.xml. Specially the `<provider>` tags.
In the best case, the build process is writing this plugin's provider tag twice, in the worst it is conflicting with another plugin.

Fell free to send me by e-mail if you prefer: andre_a_tissot@yahoo.com.br

**Comment by andrehtissot** [comment]
Closed due to lack of user's answer.

**Comment by tyduztck** [comment]
I  having this issue now. the manifest for cordova-plugin-firebase-extended-notification and cordova-plugin-file  clash. 

  <provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="android.support.v4.content.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" />
        </provider>
        <provider android:authorities="com.wallace.phr.fbenfileprovider" android:exported="false" android:grantUriPermissions="true" android:name="android.support.v4.content.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/firebaseextendednotification_provider_paths" />
        </provider>

This is what my android manifest shows when i compile the project.

**Comment by tyduztck** [comment]
I having this issue now, it seems that cordova-plugin-file and cordova-plugin-firebase-extended-notification manifest crash.

Below is my manifest.
[AndroidManifest.txt](https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification/files/2057140/AndroidManifest.txt)

**Comment by andrehtissot** [comment]
I see.
Could you tell me which versions of plugins and android platform are you using?

**Comment by tyduztck** [comment]
cordova-plugin-file 6.0.1
cordova-plugin-firebase-extended-notification 1.9.1 
android platform - android 7.0.0

**Comment by tyduztck** [comment]
So Sorry!!
It was the plugin cordova-plugin-camera making the issue! 
not cordova-plugin-file

**Comment by tyduztck** [comment]
So is cordova-plugin-file  and cordova-plugin-firebase-extended-notification clash

**Comment by tyduztck** [comment]
Hi, I removed the cordova-plugin-camera plugin and installed cordova-plugin-firebase-extended-notification, then install back cordova-plugin-camera plugin and now it works. 

Not sure why, maybe is the version of  cordova-plugin-camera plugin 

you can close this case now. Thank you.

**Comment by andrehtissot** [comment]
Okay :)
