### ISSUE TITLE
Cordova build error

### ISSUE THREAD

**Issue by tyduztck** [andrehtissot/cordova-plugin-firebase-extended-notification#22]
I have problem build my project. There is duplication on android.support.v4.content.FileProvider. 
I currently use cordova-plugin-file plugin with cordova-plugin-firebase-extended-notification plugin which causes this issue.

I do not know how to merge this together.

Below is my android manifest, please help. 
[AndroidManifest.txt](https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification/files/2057222/AndroidManifest.txt)

**Comment by tyduztck** [comment]
You can close this case now. thank you.

**Comment by andrehtissot** [comment]
Thank you :)
