### ISSUE TITLE
"openApp": true not working

### ISSUE THREAD

**Issue by tyduztck** [andrehtissot/cordova-plugin-firebase-extended-notification#23]
Hi i tested openApp, however my app cant execute when notification receive.

**Comment by andrehtissot** [comment]
I noticed that the new cordova-android building script have changed the location of AndroidManifest.xml which this plugin edits to force it as the responsible to answer for push notifications.

I tested the openApp option in Android 7 and 8 and both worked. I advice you to reinstall this plugin to get the new buildscript and rebuild the app.

If even then it does not open the app, please inform the push data payload, the version of each plugin you installed in your project and the version of android you are using to test it.

**Comment by andrehtissot** [comment]
Issue closed due to lack of information regarding the bug found and not being able to reproduce it.

**Comment by efizzy** [comment]
Hello @andrehtissot, 

Currently using this plugin on Android 10 and the "openApp": true option not working. Any ideal why this is so?
