### ISSUE TITLE
App not opening messages

### ISSUE THREAD

**Issue by aryehrein** [andrehtissot/cordova-plugin-firebase-extended-notification#25]
Hi,
I tried to send the following message from my firebase admin app (in firebase functions)
```
     const payload = {
        data: {
            dataValuesToGetWhenClickedOn: '111',
            notificationOptions: JSON.stringify({
                id: '4',
                title: 'Title test',
                text: 'Test message',
                smallIcon: 'drawable/icon',
                largeIcon: 'https://avatars2.githubusercontent.com/u/1174345?v=3&s=96',
                autoCancel: true,
                vibrate: [200,300,200,300],
                color: '0000ff',
                headsUp: true,
                sound: true
            })
        }
    };
    return firebaseAdmin.messaging().sendToDevice(tokens, payload);
```
The message is being received, because:
1.  firebaseAdmin.messaging().sendToDevice response shows OK
2. tried to catch it when app is on foreground - and everything look good

However when on background, nothing seems to happen...
Unlike in you app example, I use FirebasePlugin to catch messages.

I also tried - 
1. install FCM (in addition with FirebasePlugin) - again it caught the message but I could see it only when tapped (not sent to notification tray)
2. try to mix it together with notification message - like this:
```
const payload = {
        notification: {
          title: "try",
          body: "now",
        },
        data: {
            dataValuesToGetWhenClickedOn: '111',
            notificationOptions: JSON.stringify({
                id: '4',
                title: 'Title test',
                text: 'Test message',
                smallIcon: 'drawable/icon',
                largeIcon: 'https://avatars2.githubusercontent.com/u/1174345?v=3&s=96',
                autoCancel: true,
                vibrate: [200,300,200,300],
                color: '0000ff',
                headsUp: true,
                sound: true
            })
        }
    };
    return firebaseAdmin.messaging().sendToDevice(tokens, payload);

```
But now I only got regular message with title and body and no cool images...

**Comment by andrehtissot** [comment]
First question, why are you stringifying `notificationOptions`?

Could you try to send:
```json
{
	"to": "bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
	"data": {
		"dataValuesToGetWhenClickedOn": "111",
		"notificationOptions": {
			"id": "4",
			"title": "Title test",
			"text": "Test message",
			"smallIcon": "drawable/icon",
			"largeIcon": "https://avatars2.githubusercontent.com/u/1174345?v=3&s=96",
			"autoCancel": true,
			"vibrate": [200,300,200,300],
			"color": "0000ff",
			"headsUp": true,
			"sound": true
		}
	}
}
```

Also, do not mix `notification` and `data`. If you do, the plugin will only receive the `data` when notification is tapped.


If it still doesn't work, please let me know.

**Comment by aryehrein** [comment]
using "to" throws an error:
`Error: Messaging payload contains an invalid "to" property. Valid properties are "data" and "notification"`

not strigifying `notificationOptions` throws:
`Error: Messaging payload contains an invalid value for the "data.notificationOptions" property. Values must be strings.` (as you mentioned in other issues...)

**Comment by andrehtissot** [comment]
From the version 1.10.0 on, the plugin supports `notificationOptions` as string.

Please update and check it out.

Any issues, please let me know.
