### ISSUE TITLE
question: more apps in the same firebase proj?

### ISSUE THREAD

**Issue by maxlinux2000** [andrehtissot/cordova-plugin-firebase-extended-notification#3]
Question: How do I get more apps on the same firebase project?

To run your test app I created a project with firebase and everything worked correctly. 
Then I created another app with cordova, with another name (com.example.myapp) , and I added it to the same firebase project.

What happens is that the authorization id is the same for the two Apps, and if I remove your test app, I do not get the push messages anymore.

If I pulse in a push message sent to my app (com.example.myapp), it opens your test app ... and that hurts!

Do I have to create a project for each app?

regards
MaX

**Comment by andrehtissot** [comment]
Hi MaX,

Did you reused the "google-services.json" generated for the old (test) app?

**Comment by maxlinux2000** [comment]
No, i download another when I created the new app in the firebase console
and put in the root of the new app.
I revised the new json and my app appears inside.

Strange....

**Comment by andrehtissot** [comment]
The firebase token generate for the device should be different for each app.
So to find the new "to" parameter, you should, inside your new app, call `FCMPlugin.getToken` ([use this as an example](https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification-app-example/blob/master/firebase-extended-notification-app-example/www/index.js))

**Comment by maxlinux2000** [comment]
ok, tnx!! my fault!!
