### ISSUE TITLE
Banner Notification in iOS Even When App is open

### ISSUE THREAD

**Issue by jfbourne** [andrehtissot/cordova-plugin-firebase-extended-notification#30]
I noticed I still get banner notification even if the app is open. Is this expected behavior? I would expect to continue to receive notification on the background when the app is open but not show the iOS banner.

Thanks

**Comment by andrehtissot** [comment]
I'll take a look on it.

**Comment by jfbourne** [comment]
Thanks. I will be happy to assist anything that I can!

**Comment by andrehtissot** [comment]
I currently have no iPhone and Apple dev account to test it. Maybe I'll be able in the near future.

But I'll leave this issue open. So someone may find this, or help me with it.

**Comment by DK013** [comment]
> I currently have no iPhone and Apple dev account to test it. Maybe I'll be able in the near future.
> 
> But I'll leave this issue open. So someone may find this, or help me with it.

Hi, your plugin helped me a lot dude and I wanna return the favour. I have my apple dev account and macbook here if u wanna test stuff. I don't have a physical iOS device though

**Comment by andrehtissot** [comment]
Thank you, it's quite humbling to read your message. Unfortunately, Push notifications are not really testable on a simulator.

**Comment by andrehtissot** [comment]
I'll see what I can do to be able to test this.

**Comment by andrehtissot** [comment]
The new version 2.2.0 has the current cordova-plugin-fcm-with-dependecy-updated, which has a ton of fixes and new features.
