### ISSUE TITLE
Success to send notifications but don't display notifications on iOS device

### ISSUE THREAD

**Issue by januarsy** [andrehtissot/cordova-plugin-firebase-extended-notification#31]

**Comment by januarsy** [comment]
Can anyone help me?

# Cordova-iOS 4.5.5

**Comment by januarsy** [comment]
Are cocoapods needed in the installation?

**Comment by HazeBigya** [comment]
Did anyone solve this issue??

**Comment by andrehtissot** [comment]
Hi @HazeBigya 

It is quite delicate matter, as many things can be affecting your application.

I wrote this wiki page explaining a little of it: https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification/wiki/The-Three-Types-of-Notification-Playload

If the issue there described does not affect you, please tell more. Specially the payload sent (names can be omited, but types are important).

**Comment by andrehtissot** [comment]
> Are cocoapods needed in the installation?

Also... About cocoapods: This plugin relies on the standard `cordova plugin add ...` only.
