### ISSUE TITLE
how to send notification on multiple devices at one time, i have 20 thousand users

### ISSUE THREAD

**Issue by write2sandip** [andrehtissot/cordova-plugin-firebase-extended-notification#32]
how to send notification on multiple devices at one time, i have 20 thousand users

**Comment by andrehtissot** [comment]
You can subscribe them to `topics`.

In this page you have a simple example: https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification/wiki/How-To-Send-A-Notification-To-All-Users-(Topics)
