### ISSUE TITLE
smallIcon? How to set it, using ours custom icons?

### ISSUE THREAD

**Issue by maxlinux2000** [andrehtissot/cordova-plugin-firebase-extended-notification#5]
The plugin and the example notify.php works great, but I need to use my own app icon, instead the default gray bell from "@mipmap/icon"

I tried to put my path, like @mipmap-ldpi-v4/icon.png  but still resist me.

Do you have idea how to change it?

regards
MaX

**Comment by andrehtissot** [comment]
The `smallIcon` param, for now, only accepts resources, so you must call the way I would as an internal resource.
In your case, you could try something like `"mipmap/icon"`, then for each "kind" of android display, you can have a icon.png. Ex.: For a 240x320 display, the `"mipmap/icon"` will be loading from `"platforms/android/res/mipmap-ldpi/icon.png"`.

**Comment by maxlinux2000** [comment]
strange.... I generated the icons with "ionic resources" and they put the images in  platforms/android/res/, and i can see all sizes of icons in my app.

but setting in the script  
`"smallIcon": "@mipmap/icon"`
I receive a gray bell

setting without the "@"
`"smallIcon": "mipmap/icon"`
I receive a grey square box

I think that these icons come from system

**Comment by andrehtissot** [comment]
The bell is the default icon. The grey square box may be set from another plugin or from ionic itself. Check the images in "platforms/android/res/mipmap-*" directories.
