### ISSUE TITLE
Como implementar uma Big Image

### ISSUE THREAD

**Issue by bergfenix** [andrehtissot/cordova-plugin-firebase-extended-notification#6]
Olá André, tudo joia?

Como implementar ou usar uma imagem grande? No caso o:
.setStyle(new Notification.BigPictureStyle()
         .bigPicture(aBigBitmap))

Para expandir a notificação.

**Comment by andrehtissot** [comment]
Olá bergfenix,

Veja essa imagem,
![Ver imagem de exemplo](http://developer.boxcar.io/images/android/phone-device-big-picture.png)

Você precisa de algo como o Push Demo exibido?

Atualmente o plugin não dá suporte a esta opção.

Se quiser implementar, os arquivos que deveria alterar seriam:
* src/android/MessagingService.java; e
* src/android/Options.java.

**Comment by bergfenix** [comment]
Exatamente André, como este print que você enviou sim. 

Eu tentei editar o " src/android/MessagingService.java; " com as referências da página https://developer.android.com/reference/android/app/Notification.BigPictureStyle.html , usando como imagem "grande" como a mesma que vem das "options" da data enviada no push, mas não obtive sucesso. 

Veja a parte que editei como ficou:

`Builder builder = new Builder(this).setDefaults(0)
            .setContentTitle(options.getTitle()).setSmallIcon(options.getSmallIconResourceId())
			.setStyle(new Notification.BigPictureStyle()
			.bigPicture(options.getLargeIconBitmap())
            .setLargeIcon(options.getLargeIconBitmap()).setAutoCancel(options.isAutoCancel());`

Eu acrescentei o "setStyle" e o "bigPicture" (chamando o getLargeIconBitmap). Achei que pudesse dar certo. Agradeceria muito se pudesse me indicar o que estou fazendo de errado,sou programador PHP e estou tentando introduzir o java em meu cotidiano também.

**Comment by andrehtissot** [comment]
Posso dar uma olhada nesse final de semana se quiser.

Poderia ser algo como um parâmetro `bigPicture`?
```JSON
{
  "to" : "bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
  "data" : {
    "dataValuesToGetWhenClickedOn" : 111,
    "notificationOptions" : {
      "title" : "Title test",
      "id" : 4,
      "text" : "Test message",
      "smallIcon" : "drawable/icon",
      "largeIcon" : "https://avatars2.githubusercontent.com/u/1174345?v=3&s=96",
      "bigPicture" : "https://cloud.githubusercontent.com/assets/7321362/24875178/1e58d2ec-1ddc-11e7-96ed-ed8bf011146c.png",
      "autoCancel" : true,
      "vibrate": [200,300,200,300],
      "sound": true
    }
  }
}
```

**Comment by bergfenix** [comment]
Pode sim, claro., como você achar melhor. Certamente outros necessitarão desta função e creio que ficaria um plugin completo para push já que aceita icones personalizados e até imagem de destaque. Já pesquisei muuuuitos plugins do tipo e até o momento o seu foi o mais completo,incluindo até o arquivo PHP.

Fico imensamente agradecido se puder me ajudar com isso. Desde já, grato pela atenção e seu tempo.

**Comment by andrehtissot** [comment]
Implementado,

Qualquer coisa, avise.

https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification/wiki/Big-Picture-Option
