### ISSUE TITLE
Error: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by maxlinux2000** [andrehtissot/cordova-plugin-firebase-extended-notification#7]
Hi, as title, with the last version of this plugin I can't build, due this error on the console:

`Error: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

for the moment i'm back to 1.2.3 version

my system is ubuntu 14.04 with 
$ cordova -v
7.0.1

**Comment by andrehtissot** [comment]
I used `let` to define a variable in the hooked script, without realizing that it would not work in older node.js.

Please update and retry.
