### ISSUE TITLE
INSTALL_FAILED_CONFLICTING_PROVIDER

### ISSUE THREAD

**Issue by maxlinux2000** [andrehtissot/cordova-plugin-firebase-extended-notification#9]
I have two apps, both with firebase-exended-nofification.
Obviously the packages names an ids, are differents and I can install both in my phone.
But when I add this plugin, I can install only one, because the second one rise me the error "INSTALL_FAILED_CONFLICTING_PROVIDER"

If I remove the first app from the phone I can install the second.

If I remove the firebase-exended-nofification plugin from one of the two apps, I can install both in the phone... 

any idea how to fix it?

**Comment by andrehtissot** [comment]
For some reason the name of the file provider is global, i'll fix that.

**Comment by andrehtissot** [comment]
Please update the plugin to the version 1.4.4 and rebuild it.

If it still return this error, please reopen this issue with the AndroidManifest.xml generated attached.

**Comment by maxlinux2000** [comment]
perfect! :) it's works
